main: main.o worms.o helper.o
  gcc -o main main.o worms.o helper.o -lncurses

main.o: main.c helper.h worms.h
  gcc -c main.c -lncurses

worms.o: worms.c helper.h worms.h
  gcc -c worms.c -lncurses

helper.o: helper.c helper.h worms.h
  gcc -c helper.c -lncurses

clean:
  rm *.o main
